version: 2

project_name: irc-notes-bot

before:
  hooks:
    - go mod tidy

builds:
  - id: irc-notes-bot
    main: ./cmd/irc-notes-bot
    binary: irc-notes-bot
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ldflags:
      - -s -w -extldflags '-static' -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    files:
      - README.md
      - config.yaml

checksum:
  name_template: "checksums.txt"

changelog:
  use: github
  sort: asc
  groups:
    - title: "🚀 Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "📚 Documentation"
      regexp: '^.*?docs(\([[:word:]]+\))??!?:.+$'
      order: 2
    - title: "🔧 Maintenance"
      regexp: '^.*?(chore|ci|build|refactor|perf|test)(\([[:word:]]+\))??!?:.+$'
      order: 3
    - title: "Other"
      order: 999
  filters:
    exclude:
      - "^Merge"

release:
  github:
    owner: identw
    name: irc-notes-bot
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"
